UmbrellaApiDocBundle_api_adm_api_view:
    path: /
    defaults: { _controller: UmbrellaApiDocBundle:Api:getView }
    methods: GET

UmbrellaApiDocBundle_api_adm_api_json:
    path: /json
    defaults: { _controller: UmbrellaApiDocBundle:Api:getJson, _format: json }
    methods: GET